# Tell Java where your XAMPP MySQL database server is running
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener_db?createDatabaseIfNotExist=true

# XAMPP default username is root
spring.datasource.username=root

# XAMPP default password is blank (nothing between the equals sign and the end)
spring.datasource.password=

# Automatically build or update database tables matching our Java objects
spring.jpa.hibernate.ddl-auto=update

# Print out the database actions in the IntelliJ console so we can see it working
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379